### ISSUE TITLE
Can this script work on CDH5

### ISSUE THREAD

**Issue by bryanyang0528** [cloudera/cloudera-scripts-for-log4j#18]
Hi Team,

Thanks for the great work. The readme said `These defaults work for CM/CDH 6 and CDP 7. A different set of directories will be used for HDP.` I'm wondering to ask does this script work on CDH5. Thanks.

**Comment by jtran-cloudera** [comment]
From the current TSB, Cloudera does not believe CM5 or CDH5 to be affected by the log4j2 vulnerability. CM6 and above with CDH5 clusters are affected, and there script can be run. As CM5 uses a different set of directories, the script cannot be run on CM5 with CDH5 as-is.
