### ISSUE TITLE
Existence of unzip is not properly tested inside delete_jndi_from_jar_files

### ISSUE THREAD

**Issue by StrongestNumber9** [cloudera/cloudera-scripts-for-log4j#20]
https://github.com/cloudera/cloudera-scripts-for-log4j/blob/d30e17f9d98fb8a351bcdaffa9905dd609b8081f/cm_cdp_cdh_log4j_jndi_removal.sh#L114

```sh
./cm_cdp_cdh_log4j_jndi_removal.sh: line 114: unzip: command not found
```

**Comment by sunilgovind** [comment]
Yes. The latest commit fixes this issue. Thank you for the findings.
