### ISSUE TITLE
HDP: Symlinks to jars not getting followed and scanned for JndiLookup.class files

### ISSUE THREAD

**Issue by dins2k2** [cloudera/cloudera-scripts-for-log4j#28]
Observation from a test run of log4j patch script on HDP:

Looks like if a OS directory has symlinks to jars, its not getting followed and scanned for JndiLookup.class files.

`grep: /usr/hdp/current/phoenix-server/lib/hbase-testing-util.jar: No such file or directory`

**Test run Log:**
```
[root@server]# ./run_log4j_patcher.sh hdp
INFO : Running HDP/HDF patcher script: ./hdp_log4j_jndi_removal.sh '/usr/hdp/current /usr/hdf/current /usr/lib /var/lib' /opt/cloudera/log4shell-backup
INFO : Log file: output_run_log4j_patcher.hjH6lO
.
Removing JNDI from jar files
Running on '/usr/hdp/current'
Backing up files to '/opt/cloudera/log4shell-backup'
grep: /usr/hdp/current/hadoop-client/lib/ojdbc6.jar: No such file or directory
grep: /usr/hdp/current/hbase-client/lib/ojdbc6.jar: No such file or directory
grep: /usr/hdp/current/hbase-master/lib/ojdbc6.jar: No such file or directory
grep: /usr/hdp/current/hbase-regionserver/lib/ojdbc6.jar: No such file or directory
grep: /usr/hdp/current/phoenix-client/lib/hbase-testing-util.jar: No such file or directory
grep: /usr/hdp/current/phoenix-server/lib/hbase-testing-util.jar: No such file or directory
Running on '/usr/hdf/current'
Backing up files to '/opt/cloudera/log4shell-backup'
Running on '/usr/lib'
Backing up files to '/opt/cloudera/log4shell-backup'
Running on '/var/lib'
Backing up files to '/opt/cloudera/log4shell-backup'
Run successful
INFO : Finished
[root@server]#
```

**Symlink:**
[user@server]$ ll /usr/hdp/current/phoenix-client/lib/hbase-testing-util.jar
_lrwxrwxrwx 1 root root 52 May 22  2018 /usr/hdp/current/phoenix-client/lib/hbase-testing-util.jar -> /usr/hdp/2.6.4.0-91/hbase/lib/hbase-testing-util.jar_

Any fix for this? Or am I missing something?

**Comment by starkjs** [comment]
You don't want it to touch any symlink, they should all be ignored. 
All files should be scanned. 
Then any symlink to these files will be ok,as there is usually multiple symlinks to one file

**Comment by belugabehr** [comment]
Seems related to #26

**Comment by jtran-cloudera** [comment]
Currently, the scan does follow symlinks (though it arguably should not). Do the symlinks point to valid files?

**Comment by starkjs** [comment]
It SHOULD NOT use synlinks, as the backup will not be the true file and makes rollback hard. There is also issues with permission of the backup file, so on restore it can break access based on the systems security level with its umask setting

**Comment by dins2k2** [comment]
> Currently, the scan does follow symlinks (though it arguably should not). Do the symlinks point to valid files?

I just had a quick check, seems the symlinks pointing to the non-existing jars.

**Comment by dins2k2** [comment]
I think this issue can be closed. Thanks for all your help!
