### ISSUE TITLE
Use git best-practices: do NOT force-push into the main branch

### ISSUE THREAD

**Issue by lhoss** [cloudera/cloudera-scripts-for-log4j#34]
IMO force-push into the main branch should not be allowed at all, for many reasons:
- for one  the community/contributors here  need to all the time rebase their forks, PRs, patches 
- and it seems PRs got auto-closed because of this, including mine #2  :(
(Of course in feature branches it's OK to force-push , if it helps to keep the history cleaner etc)

Also in general would be nice if Cloudera does changes via  feature branches , as does the community
- and we would almost need some CI/CD incl. basic integration tests for this (with the many changes and contributions)

**Comment by sdevineni** [comment]
We had to do it earlier to fix the commit messages. Going forward there won't be any force pushes. 
Sorry for the trouble and thanks for bringing it up.

**Comment by sdevineni** [comment]
Every change goes through CI / CD & Testing is happening internally within cloudera.
